access==1.1.9
affine==2.4.0
altair==5.4.1
amply==0.1.6
annotated-types==0.7.0
appnope==0.1.4
asttokens==2.4.1
attrs==24.2.0
beautifulsoup4==4.12.3
branca==0.7.2
Brotli==1.1.0
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.4.0
click==8.1.7
click-plugins==1.1.1
cligj==0.7.2
colorama==0.4.6
comm==0.2.2
contextily==1.6.2
contourpy==1.3.1
cycler==0.12.1
dacite==1.8.1
debugpy==1.8.8
decorator==5.1.1
Deprecated==1.2.15
deprecation==2.1.0
descartes==1.1.0
docutils==0.21.2
esda==2.6.0
et_xmlfile==2.0.0
exceptiongroup==1.2.2
executing==2.1.0
fastjsonschema==2.20.0
fiona==1.10.1
folium==0.18.0
fonttools==4.55.0
GDAL==3.10.0
geographiclib==2.0
geopandas==1.0.1
geopy==2.4.1
giddy==2.3.5
gmpy2==2.1.5
h2==4.1.0
hpack==4.0.0
htmlmin==0.1.12
hyperframe==6.0.1
idna==3.10
ImageHash==4.3.1
importlib_metadata==8.5.0
importlib_resources==6.4.5
inequality==1.0.1
ipykernel==6.29.5
ipython==8.29.0
ipywidgets==8.1.5
jedi==0.19.2
Jinja2==3.1.4
joblib==1.4.2
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
jupyter_client==8.6.3
jupyter_core==5.7.2
jupyterlab_widgets==3.0.13
kiwisolver==1.4.7
libpysal==4.12.1
llvmlite==0.43.0
mapclassify==2.8.1
MarkupSafe==3.0.2
matplotlib==3.9.2
matplotlib-inline==0.1.7
mercantile==1.2.1
mgwr==2.2.1
momepy==0.8.1
mpmath==1.3.0
multimethod==1.12
munkres==1.1.4
narwhals==1.14.1
nbformat==5.10.4
nest_asyncio==1.6.0
networkx==3.4.2
numba==0.60.0
numpy==2.0.2
openpyxl==3.1.5
packaging==24.2
palettable==3.3.3
pandas==2.2.3
parso==0.8.4
patsy==1.0.1
pexpect==4.9.0
phik==0.11.2
pickleshare==0.7.5
pillow==11.0.0
pip==24.3.1
pkgutil_resolve_name==1.3.10
platformdirs==4.3.6
plotly==5.24.1
pointpats==2.5.1
prince==0.13.0
prompt_toolkit==3.0.48
psutil==6.1.0
ptyprocess==0.7.0
PuLP==2.8.0
pure_eval==0.2.3
pycparser==2.22
pydantic==2.10.0
pydantic_core==2.27.0
Pygments==2.18.0
pyogrio==0.10.0
pyparsing==3.2.0
pyproj==3.7.0
pysal==24.7
PySocks==1.7.1
python-dateutil==2.9.0.post0
pytz==2024.1
PyWavelets==1.7.0
PyYAML==6.0.2
pyzmq==26.2.0
quantecon==0.7.2
rasterio==1.4.2
rasterstats==0.20.0
referencing==0.35.1
requests==2.32.3
rpds-py==0.21.0
Rtree==1.3.0
scikit-learn==1.5.2
scipy==1.13.1
seaborn==0.13.2
segregation==2.5.1
setuptools==75.5.0
shapely==2.0.6
simplejson==3.19.3
six==1.16.0
snuggs==1.4.7
soupsieve==2.5
spaghetti==1.7.6
spglm==1.1.0
spint==1.0.7
splot==1.1.7
spopt==0.6.1
spreg==1.8
spvcm==0.3.0
stack-data==0.6.2
statsmodels==0.14.4
sympy==1.13.3
tenacity==9.0.0
threadpoolctl==3.5.0
tobler==0.12.0
tornado==6.4.1
tqdm==4.67.0
traitlets==5.14.3
typeguard==4.4.1
typing_extensions==4.12.2
tzdata==2024.2
unicodedata2==15.1.0
urllib3==2.2.3
visions==0.7.6
wcwidth==0.2.13
wheel==0.45.0
widgetsnbextension==4.0.13
wordcloud==0.0.0
wrapt==1.16.0
xyzservices==2024.9.0
ydata-profiling==0.0.dev0
zipp==3.21.0
zstandard==0.23.0
