name: Thesis
channels:
  - conda-forge
  - defaults
dependencies:
  - access=1.1.8
  - affine=2.4.0
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - altair=5.3.0
  - amply=0.1.6
  - annotated-types=0.7.0
  - ansi2html=1.9.2
  - anyio=4.4.0
  - aom=3.9.1
  - appnope=0.1.4
  - archspec=0.2.3
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.7.0
  - aws-c-common=0.9.23
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.9
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.0
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.27.2
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.12.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.11.0
  - azure-storage-common-cpp=12.6.0
  - azure-storage-files-datalake-cpp=12.10.0
  - babel=2.14.0
  - backports=1.0
  - backports.functools_lru_cache=2.0.0
  - beautifulsoup4=4.12.3
  - blas=2.122
  - blas-devel=3.9.0
  - bleach=6.1.0
  - blinker=1.8.2
  - blosc=1.21.6
  - boltons=24.0.0
  - bqplot=0.12.43
  - branca=0.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.32.0
  - ca-certificates=2024.7.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.3
  - cairo=1.18.0
  - catalogue=2.0.10
  - certifi=2024.7.4
  - cffi=1.16.0
  - cfitsio=4.4.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpathlib=0.16.0
  - cloudpickle=3.0.0
  - coin-or-cbc=2.10.11
  - coin-or-cgl=0.60.7
  - coin-or-clp=1.17.8
  - coin-or-osi=0.108.10
  - coin-or-utils=2.11.11
  - coincbc=2.10.11
  - colorama=0.4.6
  - colorspacious=1.1.2
  - colour=0.1.5
  - comm=0.2.2
  - conda=24.5.0
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - confection=0.1.4
  - contextily=1.6.0
  - contourpy=1.2.1
  - country_converter=1.2
  - cramjam=2.8.3
  - cryptography=42.0.8
  - cycler=0.12.1
  - cymem=2.0.8
  - cython-blis=0.7.10
  - dacite=1.8.1
  - dash=2.17.1
  - dash-core-components=2.0.0
  - dash-daq=0.5.0
  - dash-html-components=2.0.0
  - dash_colorscales=0.0.4
  - dataclasses=0.8
  - dav1d=1.2.1
  - debugpy=1.8.2
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecation=2.1.0
  - descartes=1.1.0
  - distro=1.9.0
  - docutils=0.21.2
  - dtale=3.13.1
  - earthengine-api=0.1.410
  - ee_extra=0.0.15
  - eerepr=0.0.4
  - entrypoints=0.4
  - esda=2.5.1
  - et_xmlfile=1.1.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - fastparquet=2024.5.0
  - fastremap=1.14.0
  - ffmpeg=7.0.1
  - ffmpeg-python=0.2.0
  - filelock=3.15.4
  - fiona=1.9.6
  - flask=3.0.3
  - flask-compress=1.15
  - fmt=10.2.1
  - folium=0.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - freexl=2.0.0
  - fribidi=1.0.10
  - frozendict=2.4.4
  - frozenlist=1.4.1
  - fsspec=2024.6.1
  - future=1.0.0
  - gdal=3.9.1
  - gdown=5.2.0
  - geeadd=0.5.6
  - geemap=0.32.1
  - geocoder=1.38.1
  - geographiclib=2.0
  - geojson=3.1.0
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geopy=2.4.1
  - geos=3.12.2
  - geotiff=1.7.3
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - giddy=2.3.5
  - giflib=5.2.2
  - glasbey=0.2.1
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.9
  - google-api-python-client=2.136.0
  - google-auth-httplib2=0.2.0
  - google-cloud-core=2.4.1
  - google-cloud-storage=2.17.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.7.0
  - graphite2=1.3.13
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=9.0.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - htmlmin=0.1.12
  - httpcore=1.0.5
  - httplib2=0.22.0
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - imagehash=4.3.1
  - importlib-metadata=8.0.0
  - importlib-resources=6.4.0
  - importlib_metadata=8.0.0
  - importlib_resources=6.4.0
  - inequality=1.0.1
  - ipyevents=2.0.2
  - ipyfilechooser=0.6.0
  - ipykernel=6.29.5
  - ipyleaflet=0.18.2
  - ipython=8.26.0
  - ipytree=0.2.2
  - ipywidgets=8.1.3
  - isoduration=20.11.0
  - itsdangerous=2.2.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json-c=0.17
  - json5=0.9.25
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_leaflet=0.19.1
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.2
  - jupyterlab_widgets=3.0.11
  - kealib=1.5.3
  - kiwisolver=1.4.5
  - kmodes=0.12.2
  - krb5=1.21.3
  - lame=3.100
  - langcodes=3.3.0
  - lcms2=2.16
  - lemminflect=0.2.2
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.7.4
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libblas=3.9.0
  - libboost-headers=1.85.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.8.0
  - libcxx=18.1.8
  - libdav1d7=1.4.3
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgdal=3.9.1
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.80.3
  - libgoogle-cloud=2.26.0
  - libgoogle-cloud-aiplatform=2.26.0
  - libgoogle-cloud-all=2.26.0
  - libgoogle-cloud-automl=2.26.0
  - libgoogle-cloud-bigquery=2.26.0
  - libgoogle-cloud-bigtable=2.26.0
  - libgoogle-cloud-compute=2.26.0
  - libgoogle-cloud-contentwarehouse=2.26.0
  - libgoogle-cloud-dialogflow_cx=2.26.0
  - libgoogle-cloud-dialogflow_es=2.26.0
  - libgoogle-cloud-discoveryengine=2.26.0
  - libgoogle-cloud-dlp=2.26.0
  - libgoogle-cloud-documentai=2.26.0
  - libgoogle-cloud-iam=2.26.0
  - libgoogle-cloud-logging=2.26.0
  - libgoogle-cloud-monitoring=2.26.0
  - libgoogle-cloud-oauth2=2.26.0
  - libgoogle-cloud-policytroubleshooter=2.26.0
  - libgoogle-cloud-pubsub=2.26.0
  - libgoogle-cloud-retail=2.26.0
  - libgoogle-cloud-spanner=2.26.0
  - libgoogle-cloud-speech=2.26.0
  - libgoogle-cloud-storage=2.26.0
  - libgoogle-cloud-talent=2.26.0
  - libgoogle-cloud-trace=2.26.0
  - libgrpc=1.62.2
  - libhwloc=2.11.0
  - libiconv=1.17
  - libidn2=2.3.7
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libopenvino=2024.2.0
  - libopenvino-arm-cpu-plugin=2024.2.0
  - libopenvino-auto-batch-plugin=2024.2.0
  - libopenvino-auto-plugin=2024.2.0
  - libopenvino-hetero-plugin=2024.2.0
  - libopenvino-ir-frontend=2024.2.0
  - libopenvino-onnx-frontend=2024.2.0
  - libopenvino-paddle-frontend=2024.2.0
  - libopenvino-pytorch-frontend=2024.2.0
  - libopenvino-tensorflow-frontend=2024.2.0
  - libopenvino-tensorflow-lite-frontend=2024.2.0
  - libopus=1.3.1
  - libparquet=16.1.0
  - libpng=1.6.43
  - libpq=16.3
  - libprotobuf=4.25.3
  - libpysal=4.11.0
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libsolv=0.7.29
  - libspatialindex=2.0.0
  - libspatialite=5.1.0
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtasn1=4.19.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libvpx=1.14.1
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libzip=1.10.1
  - libzlib=1.3.1
  - littleutils=0.2.2
  - llvm-openmp=18.1.8
  - llvmlite=0.43.0
  - logzero=1.7.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.6.1
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - menuinst=2.1.1
  - mercantile=1.2.1
  - mgwr=2.2.1
  - minizip=4.0.7
  - missingno=0.5.2
  - mistune=3.0.2
  - momepy=0.7.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.0.5
  - multimethod=1.12
  - munch=4.0.0
  - munkres=1.1.4
  - murmurhash=1.0.10
  - natsort=8.4.0
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.3
  - nltk=3.8.1
  - notebook-shim=0.2.4
  - nspr=4.35
  - nss=3.102
  - numba=0.60.0
  - openblas=0.3.27
  - openh264=2.4.1
  - openjpeg=2.5.2
  - openpyxl=3.1.4
  - openssl=3.3.1
  - orc=2.0.1
  - osmnx=1.9.3
  - outdated=0.2.2
  - overrides=7.7.0
  - p11-kit=0.24.1
  - packaging=24.1
  - pandas-flavor=0.6.0
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pathy=0.10.3
  - patsy=0.5.6
  - pcre2=10.44
  - pexpect=4.9.0
  - phik=0.11.2
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pingouin=0.5.4
  - pip=24.0
  - pixman=0.43.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - plotly=5.22.0
  - pointpats=2.5.0
  - polars=1.1.0
  - poppler=24.07.0
  - poppler-data=0.4.12
  - postgresql=16.3
  - preshed=3.0.9
  - prince=0.13.0
  - proj=9.4.1
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - proto-plus=1.23.0
  - protobuf=4.25.3
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pulp=2.8.0
  - pure_eval=0.2.2
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pycrs=1.0.2
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pygments=2.18.0
  - pynndescent=0.5.13
  - pyobjc-core=10.3.1
  - pyobjc-framework-cocoa=10.3.1
  - pyogrio=0.8.0
  - pyopenssl=24.0.0
  - pyparsing=3.1.2
  - pypdf=4.2.0
  - pyperclip=1.9.0
  - pyproj=3.6.1
  - pysal=23.7
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.11.9
  - python-box=7.2.0
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytz=2024.1
  - pyu2f=0.1.5
  - pywavelets=1.6.0
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - quantecon=0.7.2
  - rasterio=1.3.10
  - rasterstats=0.19.0
  - ratelim=0.1.6
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - regex=2024.5.15
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.32.3
  - retrying=1.3.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.1
  - rpds-py=0.19.0
  - rsa=4.9
  - rtree=1.3.0
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - ruff=0.5.1
  - sankee=0.2.5
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - scooby=0.10.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - segregation=2.5
  - send2trash=1.8.3
  - setuptools=70.2.0
  - shap=0.45.1
  - shapely=2.0.4
  - shellingham=1.5.4
  - simplejson=3.19.2
  - six=1.16.0
  - slicer=0.0.8
  - smart-open=6.4.0
  - smart_open=6.4.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - snuggs=1.4.7
  - soupsieve=2.5
  - spacy=3.7.4
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - spaghetti=1.7.6
  - spdlog=1.13.0
  - spglm=1.1.0
  - spint=1.0.7
  - splot=1.1.5.post1
  - spopt=0.6.1
  - spreg=1.5.0
  - spvcm=0.3.0
  - sqlite=3.46.0
  - squarify=0.4.3
  - srsly=2.4.8
  - stack_data=0.6.2
  - statsmodels=0.14.2
  - strsimpy=0.1.9
  - svt-av1=2.1.2
  - sweetviz=2.3.1
  - sympy=1.12.1
  - tableone=0.9.1
  - tabulate=0.9.0
  - tangled-up-in-unicode=0.2.0
  - tbb=2021.12.0
  - tenacity=8.5.0
  - terminado=0.18.1
  - thinc=8.2.3
  - threadpoolctl=3.5.0
  - tiledb=2.24.2
  - tinycss2=1.3.0
  - tk=8.6.13
  - tobler=0.11.2
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.1
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - traittypes=0.2.1
  - truststore=0.8.0
  - typer=0.9.4
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzcode=2024a
  - tzdata=2024a
  - umap-learn=0.5.5
  - uri-template=1.3.0
  - uriparser=0.9.8
  - uritemplate=4.1.1
  - urllib3=2.2.2
  - visions=0.7.6
  - wasabi=1.1.2
  - wcwidth=0.2.13
  - weasel=0.3.4
  - webcolors=24.6.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.0.3
  - wheel=0.43.0
  - whitebox=2.3.4
  - whiteboxgui=2.3.0
  - widgetsnbextension=4.0.11
  - wordcloud=1.9.3
  - x264=1!164.3095
  - x265=3.5
  - xarray=2024.6.0
  - xerces-c=3.2.5
  - xlrd=2.0.1
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2024.6.0
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yarl=1.9.4
  - yellowbrick=1.5
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.3.1
  - zstandard=0.22.0
  - zstd=1.5.6
  - pip:
      - astor==0.8.1
      - autoelbow==0.0.4
      - configparser==5.3.0
      - coverage==7.2.7
      - dash-bootstrap-components==1.4.1
      - dash-table==5.0.0
      - duckdb==0.10.2
      - en-core-web-sm==3.5.0
      - faker==19.13.0
      - flask-ngrok==0.0.25
      - geotable==0.4.2.8
      - google-ai-generativelanguage==0.4.0
      - google-api-core==2.17.1
      - google-auth==2.28.2
      - google-generativeai==0.4.0
      - googleapis-common-protos==1.62.0
      - grpcio==1.62.1
      - grpcio-status==1.62.1
      - iniconfig==2.0.0
      - invisibleroads-macros==0.9.5.1
      - kaleido==0.2.1
      - numpy==1.23.5
      - openai==1.30.1
      - pandas==1.5.3
      - pandasai==2.0.40
      - pluggy==1.0.0
      - pprintpp==0.4.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycountry==22.3.5
      - pycountry-convert==0.7.2
      - pytest==7.3.1
      - pytest-cov==4.1.0
      - pytest-mock==3.10.0
      - python-dotenv==1.0.1
      - repoze-lru==0.7
      - typeguard==2.13.3
      - utm==0.7.0
      - ydata-profiling==4.5.1
